#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql: TRACE
logging.level.net.ttddyy.dsproxy.listener: DEBUG

spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crudstar
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      idle-timeout: 300000
      minimum-idle: 5
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        metadata_builder_contributor: com.ethanaa.crudstar.repository.specification.SQLFunctionContributor
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    generate-ddl: true
  flyway:
    enabled: false
